version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: timetrack-db
    restart: always
    environment:
      POSTGRES_USER: timetrack
      POSTGRES_PASSWORD: timetrack_pass
      POSTGRES_DB: timetrack_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: timetrack-adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data:
