"""Add ApprovalDraft model

Revision ID: 0553d80875eb
Revises: 9c26928a2168
Create Date: 2026-04-22 00:07:47.028151

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0553d80875eb'
down_revision: Union[str, None] = '9c26928a2168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_type', sa.String(), nullable=False),
    sa.Column('draft_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('ai_reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_drafts_team_id'), 'approval_drafts', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_drafts_team_id'), table_name='approval_drafts')
    op.drop_table('approval_drafts')
    # ### end Alembic commands ###
