"""add_google_calendar_fields_to_tasks

Revision ID: 2a5e0dc0cbc0
Revises: bee52b0f9b52
Create Date: 2026-04-23 19:47:08.164662

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5e0dc0cbc0'
down_revision: Union[str, None] = 'bee52b0f9b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_lead_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.create_index(op.f('ix_agent_tasks_team_id'), 'agent_tasks', ['team_id'], unique=False)
    op.drop_constraint(op.f('fk_approval_drafts_lead'), 'approval_drafts', type_='foreignkey')
    op.drop_column('approval_drafts', 'run_id')
    op.drop_column('approval_drafts', 'lead_id')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_leads_next_follow_up'), table_name='leads')
    op.drop_index(op.f('ix_llm_usage_team_date'), table_name='llm_usage_logs')
    op.create_index(op.f('ix_llm_usage_logs_team_id'), 'llm_usage_logs', ['team_id'], unique=False)
    op.create_foreign_key(None, 'llm_usage_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_meetings_scheduled_at'), table_name='meetings')
    op.drop_index(op.f('ix_memory_chunks_embedding'), table_name='memory_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_memory_chunks_team_entity'), table_name='memory_chunks')
    op.create_index(op.f('ix_memory_chunks_team_id'), 'memory_chunks', ['team_id'], unique=False)
    op.drop_column('memory_chunks', 'embedding')
    op.add_column('tasks', sa.Column('google_event_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('google_calendar_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'google_calendar_link')
    op.drop_column('tasks', 'google_event_id')
    op.add_column('memory_chunks', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_memory_chunks_team_id'), table_name='memory_chunks')
    op.create_index(op.f('ix_memory_chunks_team_entity'), 'memory_chunks', ['team_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_memory_chunks_embedding'), 'memory_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_meetings_scheduled_at'), 'meetings', ['scheduled_at'], unique=False)
    op.drop_constraint(None, 'llm_usage_logs', type_='foreignkey')
    op.drop_index(op.f('ix_llm_usage_logs_team_id'), table_name='llm_usage_logs')
    op.create_index(op.f('ix_llm_usage_team_date'), 'llm_usage_logs', ['team_id', 'usage_date'], unique=False)
    op.create_index(op.f('ix_leads_next_follow_up'), 'leads', ['next_follow_up_at'], unique=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.add_column('approval_drafts', sa.Column('lead_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('approval_drafts', sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_approval_drafts_lead'), 'approval_drafts', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_tasks_team_id'), table_name='agent_tasks')
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_lead_id'), 'agent_runs', ['lead_id'], unique=False)
    # ### end Alembic commands ###
