"""Add api keys to team and tutorial state to user

Revision ID: 527239486320
Revises: 2a5e0dc0cbc0
Create Date: 2026-04-24 17:02:17.376497

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '527239486320'
down_revision: Union[str, None] = '2a5e0dc0cbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('openai_api_key', sa.String(length=255), nullable=True))
    op.add_column('teams', sa.Column('anthropic_api_key', sa.String(length=255), nullable=True))
    op.add_column('teams', sa.Column('gemini_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('has_seen_tutorial', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_seen_tutorial')
    op.drop_column('teams', 'gemini_api_key')
    op.drop_column('teams', 'anthropic_api_key')
    op.drop_column('teams', 'openai_api_key')
    # ### end Alembic commands ###
