"""Add team_id to pipeline models

Revision ID: a43b73f228d2
Revises: 3f75403bd173
Create Date: 2026-04-22 16:35:13.931429

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43b73f228d2'
down_revision: Union[str, None] = '3f75403bd173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'custom_fields', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'deal_stages', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deal_stages', type_='foreignkey')
    op.drop_constraint(None, 'custom_fields', type_='foreignkey')
    # ### end Alembic commands ###
